[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-banking-bench"
version = "1.4.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
clap = "2.33.1"
crossbeam-channel = "0.4"
log = "0.4.6"
rand = "0.7.0"
rayon = "1.4.0"
solana-core = { path = "../core", version = "1.4.17" }
solana-clap-utils = { path = "../clap-utils", version = "1.4.17" }
solana-streamer = { path = "../streamer", version = "1.4.17" }
solana-perf = { path = "../perf", version = "1.4.17" }
solana-ledger = { path = "../ledger", version = "1.4.17" }
solana-logger = { path = "../logger", version = "1.4.17" }
solana-runtime = { path = "../runtime", version = "1.4.17" }
solana-measure = { path = "../measure", version = "1.4.17" }
solana-sdk = { path = "../sdk", version = "1.4.17" }
solana-version = { path = "../version", version = "1.4.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
